name: fcm_flutter_demo
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }
  fl_chart: ^1.1.1
  fuzzy_cmeans:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true