name: Build

on:
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]

jobs:
  dart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Analyze code
        run: dart analyze --fatal-infos --fatal-warnings
      - name: Run tests
        run: dart test